### ISSUE TITLE
Problem with migrations

### ISSUE THREAD

**Issue by kirillsalykin** [maxcountryman/underway#21] opened 2024-10-23 08:10 UTC
I have next code which creates a db pool and runs a migration:
```
use sqlx::postgres::{PgConnectOptions, PgPoolOptions};
use sqlx::PgPool;
use underway;

use crate::configuration::DatabaseConfig;

impl From<DatabaseConfig> for PgConnectOptions {
    fn from(config: DatabaseConfig) -> Self {
        PgConnectOptions::new()
            .host(&config.host)
            .port(config.port)
            .username(&config.username)
            .password(&config.password)
            .database(&config.database)
    }
}

pub async fn get_connection_pool(config: DatabaseConfig) -> PgPool {
    let pool = PgPoolOptions::new()
        .connect_with(config.into())
        .await
        .expect("fail to connect to db");

    underway::MIGRATOR.run(&pool).await.unwrap();

    // TODO: handle errors
    sqlx::migrate!("./migrations").run(&pool).await.unwrap();

    pool
}
```

Unfortunately it keeps failing with this:

```
thread 'main' panicked at /Users/kirill/Dev/Playground/prostor/src/backend/src/database.rs:27:53:
called `Result::unwrap()` on an `Err` value: VersionMissing(20240921151751)
```

which is underway migration.

sqlx knows about `20240921151751` migration because it is in _migrations table, but it is missing from the `migrations` directory.

if you change order of migrators - underway migrator will start to complain about missing migrations from the project.

**Comment by kirillsalykin** [comment] 2024-10-23 08:39
I dont think there is a way to add multiple sources for migrations in sqlx.

Options:
1. turn on `ignore-missing`, which probably nice to have, so not the best option
2. copy manually migration from the crate
3. copy automatically migration from the crate
4. ask sqlx to support multiple sources

**Comment by kirillsalykin** [comment] 2024-10-23 08:57
FYI: https://github.com/launchbadge/sqlx/issues/3573

**Comment by maxcountryman** [comment] 2024-10-23 11:29
This is a dupe of https://github.com/maxcountryman/underway/issues/11

**Closed** 2024-10-23 11:29 UTC
